### ISSUE TITLE
`getContractsForOwner` returns same contract several times

### ISSUE THREAD

**Issue by taeguk** [alchemyplatform/alchemy-sdk-js#305] opened 2023-04-13 09:36 UTC
### [REQUIRED] Describe the problem

It is a bug for alchemy endpoint.
When using `getContractsForOwner` with `orderBy=transferTime`, it returns incorrect result.

For example,
```js
const options = {method: 'GET', headers: {accept: 'application/json'}};

fetch('https://eth-mainnet.g.alchemy.com/nft/v2/docs-demo/getContractsForOwner?owner=0xafb3fDe713608D4276E63754F54298c050Cf6620&pageSize=100&withMetadata=true&orderBy=transferTime', options)
  .then(response => response.json())
  .then(response => console.log(response))
  .catch(err => console.error(err));
```
it returns same contract five times:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/9107889/231719034-0b6dfe65-564c-4171-819c-ec295445f4fa.png">

**Comment by ayang-rkjs** [comment] 2023-04-14 16:52
Hello taeguk, thanks for the report! We've identified the root cause and pushed a fix for this error. As a show of appreciation for reporting this bug, and for using our product, we'd love to send you some Alchemy swag! I sent a link to your email that you can use to claim the swag. Thanks for helping make our product better! 💪

**Comment by thebrianchen** [comment] 2023-04-14 18:03
Marking the issue as closed since it's fixed on the backend!

**Closed by thebrianchen** 2023-04-14 18:03 UTC
Labels: bug
